### PR TITLE
Added deduper application and moved the example to deduper package

### PR DESCRIPTION
**Pull request by otterc**

### CODE REVIEW

**Comment by tweise** [comment]
Any idea what creates the 1 2 3 directories?

```
hdev@hdev-vm:~/devel/dt/apex-samples/mydtapp1$ ls
1  2  3  pom.xml  src  target  XmlJavadocCommentsExtractor.xsl
```

**Comment by otterc** [comment]
Yes this because of the AsyncStorrageAgent leaving behind stray folders. There was a big debate about this  sometime back.

**Comment by tweise** [comment]
Yes, but I thought that was fixed?

**Comment by otterc** [comment]
It is fixed in 3.2.0 I reckon

**Pull request merged**
